### ISSUE TITLE
Cannot build on Alpine Linux 3.9.4 (openssl 1.1.1b-r1)

### ISSUE THREAD

**Issue by bombsimon** [gost-engine/engine#145]
Not sure if I'm missing something obvious here but I cannot build the master branch with `openssl 1.1.1b-r1` installed with `apk` under Alpine Linux 3.9.4. I don't have any problems if I use the tag `v1.1.0.3`. The last working commit for me is `0aac5d6` before fix of constification.

Any help would be much appreciated!

## Setup to reproduce

```sh
$ docker run -it --rm alpine:3.9.4
```
<details>
<summary>apk add --update cmake git g++ gcc make openssl openssl-dev</summary>

```sh
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/36) Installing libattr (2.4.47-r7)
(2/36) Installing libacl (2.2.52-r5)
(3/36) Installing libbz2 (1.0.6-r6)
(4/36) Installing expat (2.2.6-r0)
(5/36) Installing lz4-libs (1.8.3-r2)
(6/36) Installing xz-libs (5.2.4-r0)
(7/36) Installing libarchive (3.3.2-r4)
(8/36) Installing ca-certificates (20190108-r0)
(9/36) Installing nghttp2-libs (1.35.1-r0)
(10/36) Installing libssh2 (1.8.2-r0)
(11/36) Installing libcurl (7.64.0-r1)
(12/36) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(13/36) Installing ncurses-terminfo (6.1_p20190105-r0)
(14/36) Installing ncurses-libs (6.1_p20190105-r0)
(15/36) Installing libgcc (8.3.0-r0)
(16/36) Installing rhash-libs (1.3.6-r2)
(17/36) Installing libstdc++ (8.3.0-r0)
(18/36) Installing libuv (1.23.2-r0)
(19/36) Installing cmake (3.13.0-r0)
(20/36) Installing binutils (2.31.1-r2)
(21/36) Installing gmp (6.1.2-r1)
(22/36) Installing isl (0.18-r0)
(23/36) Installing libgomp (8.3.0-r0)
(24/36) Installing libatomic (8.3.0-r0)
(25/36) Installing mpfr3 (3.1.5-r1)
(26/36) Installing mpc1 (1.0.3-r1)
(27/36) Installing gcc (8.3.0-r0)
(28/36) Installing musl-dev (1.1.20-r4)
(29/36) Installing libc-dev (0.7.1-r0)
(30/36) Installing g++ (8.3.0-r0)
(31/36) Installing pcre2 (10.32-r1)
(32/36) Installing git (2.20.1-r0)
(33/36) Installing make (4.2.1-r2)
(34/36) Installing openssl (1.1.1b-r1)
(35/36) Installing pkgconf (1.6.0-r0)
(36/36) Installing openssl-dev (1.1.1b-r1)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 231 MiB in 50 packages
```
</details>

<details>
<summary>mkdir /test && cd /test && git clone https://github.com/gost-engine/engine.git</summary>

```sh 
/test # git clone https://github.com/gost-engine/engine.git
Cloning into 'engine'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1554 (delta 0), reused 2 (delta 0), pack-reused 1550
Receiving objects: 100% (1554/1554), 1.00 MiB | 2.15 MiB/s, done.
Resolving deltas: 100% (973/973), done.
```
</details>

<details>
<summary>mkdir -p engine/build && cd engine/build</summary>
</details>

<details>
<summary>cmake -DCMAKE_BUILD_TYPE=Release ..</summary>

```sh
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenSSL: /usr/lib/libcrypto.so (found suitable version "1.1.1b", minimum required is "1.1.1")
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- LITTLE_ENDIAN
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /test/engine/build
```
</details>

And this is where it fails

```sh
/test/engine/build # cmake --build . --target install --config Release
Scanning dependencies of target gost_core
[  1%] Building C object CMakeFiles/gost_core.dir/gost89.c.o
[  3%] Building C object CMakeFiles/gost_core.dir/gosthash.c.o
[  5%] Building C object CMakeFiles/gost_core.dir/gosthash2012.c.o
[  7%] Building C object CMakeFiles/gost_core.dir/gost_grasshopper_core.c.o
[  9%] Building C object CMakeFiles/gost_core.dir/gost_grasshopper_defines.c.o
[ 11%] Building C object CMakeFiles/gost_core.dir/gost_grasshopper_galois_precompiled.c.o
[ 12%] Building C object CMakeFiles/gost_core.dir/gost_grasshopper_precompiled.c.o
[ 14%] Building C object CMakeFiles/gost_core.dir/gost_grasshopper_cipher.c.o
[ 16%] Building C object CMakeFiles/gost_core.dir/gost_ec_keyx.c.o
[ 18%] Building C object CMakeFiles/gost_core.dir/gost_ec_sign.c.o
[ 20%] Building C object CMakeFiles/gost_core.dir/gost_omac.c.o
[ 22%] Building C object CMakeFiles/gost_core.dir/gost_omac_acpkm.c.o
[ 24%] Linking C static library libgost_core.a
[ 24%] Built target gost_core
Scanning dependencies of target gost_engine
[ 25%] Building C object CMakeFiles/gost_engine.dir/e_gost_err.c.o
[ 27%] Building C object CMakeFiles/gost_engine.dir/gost_asn1.c.o
[ 29%] Building C object CMakeFiles/gost_engine.dir/gost_crypt.c.o
[ 31%] Building C object CMakeFiles/gost_engine.dir/gost_ctl.c.o
[ 33%] Building C object CMakeFiles/gost_engine.dir/gost_eng.c.o
[ 35%] Building C object CMakeFiles/gost_engine.dir/gost_keywrap.c.o
[ 37%] Building C object CMakeFiles/gost_engine.dir/gost_params.c.o
[ 38%] Building C object CMakeFiles/gost_engine.dir/gost_keyexpimp.c.o
[ 40%] Building C object CMakeFiles/gost_engine.dir/gost_ameth.c.o
[ 42%] Building C object CMakeFiles/gost_engine.dir/gost_md.c.o
[ 44%] Building C object CMakeFiles/gost_engine.dir/gost_md2012.c.o
[ 46%] Building C object CMakeFiles/gost_engine.dir/gost_pmeth.c.o
/test/engine/gost_pmeth.c: In function 'pkey_gost_copy':
/test/engine/gost_pmeth.c:62:38: error: passing argument 1 of 'EVP_PKEY_CTX_get_data' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
     src_data = EVP_PKEY_CTX_get_data(src);
                                      ^~~
In file included from /test/engine/gost_pmeth.c:10:
/usr/include/openssl/evp.h:1370:7: note: expected 'EVP_PKEY_CTX *' {aka 'struct evp_pkey_ctx_st *'} but argument is of type 'const EVP_PKEY_CTX *' {aka 'const struct evp_pkey_ctx_st *'}
 void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
       ^~~~~~~~~~~~~~~~~~~~~
/test/engine/gost_pmeth.c: In function 'pkey_gost_mac_copy':
/test/engine/gost_pmeth.c:573:38: error: passing argument 1 of 'EVP_PKEY_CTX_get_data' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
     src_data = EVP_PKEY_CTX_get_data(src);
                                      ^~~
In file included from /test/engine/gost_pmeth.c:10:
/usr/include/openssl/evp.h:1370:7: note: expected 'EVP_PKEY_CTX *' {aka 'struct evp_pkey_ctx_st *'} but argument is of type 'const EVP_PKEY_CTX *' {aka 'const struct evp_pkey_ctx_st *'}
 void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
       ^~~~~~~~~~~~~~~~~~~~~
/test/engine/gost_pmeth.c: In function 'register_pmeth_gost':
/test/engine/gost_pmeth.c:1052:40: error: passing argument 2 of 'EVP_PKEY_meth_set_copy' from incompatible pointer type [-Werror=incompatible-pointer-types]
         EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                        ^~~~~~~~~~~~~~~~~~
In file included from /test/engine/gost_pmeth.c:10:
/usr/include/openssl/evp.h:1422:35: note: expected 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)'} but argument is of type 'int (*)(EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)'}
                             int (*copy) (EVP_PKEY_CTX *dst,
                             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                                          EVP_PKEY_CTX *src));
                                          ~~~~~~~~~~~~~~~~~~
/test/engine/gost_pmeth.c:1062:40: error: passing argument 2 of 'EVP_PKEY_meth_set_copy' from incompatible pointer type [-Werror=incompatible-pointer-types]
         EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                        ^~~~~~~~~~~~~~~~~~
In file included from /test/engine/gost_pmeth.c:10:
/usr/include/openssl/evp.h:1422:35: note: expected 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)'} but argument is of type 'int (*)(EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)'}
                             int (*copy) (EVP_PKEY_CTX *dst,
                             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                                          EVP_PKEY_CTX *src));
                                          ~~~~~~~~~~~~~~~~~~
/test/engine/gost_pmeth.c:1072:40: error: passing argument 2 of 'EVP_PKEY_meth_set_copy' from incompatible pointer type [-Werror=incompatible-pointer-types]
         EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                        ^~~~~~~~~~~~~~~~~~
In file included from /test/engine/gost_pmeth.c:10:
/usr/include/openssl/evp.h:1422:35: note: expected 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)'} but argument is of type 'int (*)(EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)'}
                             int (*copy) (EVP_PKEY_CTX *dst,
                             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                                          EVP_PKEY_CTX *src));
                                          ~~~~~~~~~~~~~~~~~~
/test/engine/gost_pmeth.c:1083:40: error: passing argument 2 of 'EVP_PKEY_meth_set_copy' from incompatible pointer type [-Werror=incompatible-pointer-types]
         EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                        ^~~~~~~~~~~~~~~~~~
In file included from /test/engine/gost_pmeth.c:10:
/usr/include/openssl/evp.h:1422:35: note: expected 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)'} but argument is of type 'int (*)(EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)'}
                             int (*copy) (EVP_PKEY_CTX *dst,
                             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                                          EVP_PKEY_CTX *src));
                                          ~~~~~~~~~~~~~~~~~~
/test/engine/gost_pmeth.c:1091:36: error: passing argument 2 of 'EVP_PKEY_meth_set_copy' from incompatible pointer type [-Werror=incompatible-pointer-types]
     EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_copy);
                                    ^~~~~~~~~~~~~~
In file included from /test/engine/gost_pmeth.c:10:
/usr/include/openssl/evp.h:1422:35: note: expected 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)'} but argument is of type 'int (*)(EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' {aka 'int (*)(struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)'}
                             int (*copy) (EVP_PKEY_CTX *dst,
                             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                                          EVP_PKEY_CTX *src));
                                          ~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/gost_engine.dir/build.make:206: CMakeFiles/gost_engine.dir/gost_pmeth.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:375: CMakeFiles/gost_engine.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

## Working on tag v1.1.0.3

<details>
<summary>It works fine with the latest release `v1.1.0.3`</summary>

```sh
/test/engine/build # git checkout v1.1.0.3
Note: checking out 'v1.1.0.3'.
[...]

/test/engine/build # cmake --build . --config Release
-- LITTLE_ENDIAN
-- Configuring done
-- Generating done
-- Build files have been written to: /test/engine/build
Scanning dependencies of target gost
[  3%] Building C object CMakeFiles/gost.dir/gost_ec_keyx.c.o
[  7%] Building C object CMakeFiles/gost.dir/gost_ec_sign.c.o
[ 10%] Building C object CMakeFiles/gost.dir/gost89.c.o
[ 14%] Building C object CMakeFiles/gost.dir/gosthash.c.o
[ 17%] Building C object CMakeFiles/gost.dir/gost_grasshopper_core.c.o
[ 21%] Building C object CMakeFiles/gost.dir/gost_grasshopper_defines.c.o
[ 25%] Building C object CMakeFiles/gost.dir/gost_grasshopper_galois_precompiled.c.o
[ 28%] Building C object CMakeFiles/gost.dir/gost_grasshopper_precompiled.c.o
[ 32%] Building C object CMakeFiles/gost.dir/gost_grasshopper_cipher.c.o
[ 35%] Building C object CMakeFiles/gost.dir/gost_grasshopper_mac.c.o
[ 39%] Building C object CMakeFiles/gost.dir/gosthash2012.c.o
[ 42%] Linking C static library libgost.a
[ 42%] Built target gost
Scanning dependencies of target gostsum
[ 46%] Building C object CMakeFiles/gostsum.dir/gostsum.c.o
[ 50%] Linking C executable ../bin/gostsum
[ 50%] Built target gostsum
Scanning dependencies of target gost12sum
[ 53%] Building C object CMakeFiles/gost12sum.dir/gost12sum.c.o
[ 57%] Linking C executable ../bin/gost12sum
[ 57%] Built target gost12sum
Scanning dependencies of target gost_engine
[ 60%] Building C object CMakeFiles/gost_engine.dir/e_gost_err.c.o
[ 64%] Building C object CMakeFiles/gost_engine.dir/gost_asn1.c.o
[ 67%] Building C object CMakeFiles/gost_engine.dir/gost_crypt.c.o
[ 71%] Building C object CMakeFiles/gost_engine.dir/gost_ctl.c.o
[ 75%] Building C object CMakeFiles/gost_engine.dir/gost_eng.c.o
[ 78%] Building C object CMakeFiles/gost_engine.dir/gost_keywrap.c.o
[ 82%] Building C object CMakeFiles/gost_engine.dir/gost_params.c.o
[ 85%] Building C object CMakeFiles/gost_engine.dir/gost_ameth.c.o
[ 89%] Building C object CMakeFiles/gost_engine.dir/gost_md.c.o
[ 92%] Building C object CMakeFiles/gost_engine.dir/gost_md2012.c.o
[ 96%] Building C object CMakeFiles/gost_engine.dir/gost_pmeth.c.o
[100%] Linking C shared module ../bin/gost.so
[100%] Built target gost_engine
```
</details>

**Comment by bombsimon** [comment]
I'm sorry for this ticket, after writing down the steps to reproduce I now see the note in the README:

> DO NOT TRY BUILDING MASTER BRANCH AGAINST openssl 1.1.1! Use 1_1_0 branch instead!

I'll use the `v.1.1.0.3` tag instead! Again, sorry!
