### ISSUE TITLE
Fails to build with OpenSSL_1_1_1

### ISSUE THREAD

**Issue by mouse07410** [gost-engine/engine#154]
The `README.md` does say that it doesn't work - but since 1.1.1 is the current standard and downgrading to 1.1.0 is both impractical and non-attractive - perhaps you can update the code to work with 1.1.1?

`master` branch fails compilation:
```
[ 37%] Building C object CMakeFiles/gost_engine.dir/gost_pmeth.c.o
/Users/ur20980/src/engine/gost_pmeth.c:62:38: error: passing 'const EVP_PKEY_CTX *' (aka 'const struct evp_pkey_ctx_st *')
      to parameter of type 'EVP_PKEY_CTX *' (aka 'struct evp_pkey_ctx_st *') discards qualifiers
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    src_data = EVP_PKEY_CTX_get_data((const EVP_PKEY_CTX *)src);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1371:43: note: passing argument to parameter 'ctx' here
void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
                                          ^
/Users/ur20980/src/engine/gost_pmeth.c:573:38: error: passing 'const EVP_PKEY_CTX *'
      (aka 'const struct evp_pkey_ctx_st *') to parameter of type 'EVP_PKEY_CTX *' (aka 'struct evp_pkey_ctx_st *')
      discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    src_data = EVP_PKEY_CTX_get_data(src);
                                     ^~~
/opt/local/include/openssl/evp.h:1371:43: note: passing argument to parameter 'ctx' here
void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
                                          ^
/Users/ur20980/src/engine/gost_pmeth.c:1052:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1062:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1072:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1083:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1091:36: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
    EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_copy);
                                   ^~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
7 errors generated.
make[2]: *** [CMakeFiles/gost_engine.dir/gost_pmeth.c.o] Error 1
```
 But if `-Wno-incompatible-pointer-types` is added, it compiles OK, but fails one test:
```
$ make test
Running tests...
Test project /Users/ur20980/src/engine/build
      Start  1: digest
 1/10 Test  #1: digest ...........................   Passed    0.01 sec
      Start  2: curves
 2/10 Test  #2: curves ...........................   Passed    0.03 sec
      Start  3: parameters
 3/10 Test  #3: parameters .......................   Passed    0.03 sec
      Start  4: sign/verify
 4/10 Test  #4: sign/verify ......................   Passed    0.04 sec
      Start  5: TLS
 5/10 Test  #5: TLS ..............................   Passed    0.52 sec
      Start  6: context
 6/10 Test  #6: context ..........................   Passed    0.01 sec
      Start  7: grasshopper
 7/10 Test  #7: grasshopper ......................   Passed    0.04 sec
      Start  8: keyexpimp
 8/10 Test  #8: keyexpimp ........................   Passed    0.01 sec
      Start  9: gost89
 9/10 Test  #9: gost89 ...........................   Passed    0.00 sec
      Start 10: engine
10/10 Test #10: engine ...........................***Failed    0.14 sec

90% tests passed, 1 tests failed out of 10

Total Test time (real) =   0.85 sec

The following tests FAILED:
	 10 - engine (Failed)
Errors while running CTest
make: *** [test] Error 8
```
Here's the log: 
[LastTest.master.log.txt](https://github.com/gost-engine/engine/files/3411624/LastTest.master.log.txt)

Branch `openssl_1_1_0` compiles fine, but fails the same (presumably) test:
```
Running tests...
Test project /Users/ur20980/src/engine/build
    Start 1: engine
1/2 Test #1: engine ...........................***Failed    0.99 sec
    Start 2: grasshopper
2/2 Test #2: grasshopper ......................   Passed    0.01 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   1.01 sec

The following tests FAILED:
	  1 - engine (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Here's the log from `openssl_1_1_0` branch of this repo, compiled with the standard (Macports-installed) OpenSSL_1_1_1c: 
[LastTest.log.txt](https://github.com/gost-engine/engine/files/3411575/LastTest.log.txt)

**Comment by beldmit** [comment]
Ветка master не предназначена для работы с 1.1.1.
В ветке openssl_1_1_0 всё, что поддерживается в 1.1.1, есть. 
Новая функциональность будет совместима только с master.

**Comment by mouse07410** [comment]
> В ветке openssl_1_1_0 всё, что поддерживается в 1.1.1, есть.

Которую из трёх применять?
```
  remotes/origin/openssl_1_1_0
  remotes/origin/openssl_1_1_0_release1
  remotes/origin/openssl_1_1_0_release2
```

**Comment by beldmit** [comment]
remotes/origin/openssl_1_1_0_release2

**Comment by mouse07410** [comment]
```
$ env | grep OPENSSL
OPENSSL_LIB_DIR=/opt/local/lib
OPENSSL_INCLUDE_DIR=/opt/local/include
OPENSSL_CFLAGS=-Os -Ofast -std=gnu17 -march=native -I/opt/local/include
OPENSSL_CONF=/opt/local/etc/openssl/openssl.cnf
$ cmake ..
-- The C compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /opt/local/bin/clang
-- Check for working C compiler: /opt/local/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using Clang and adding -Qunused-arguments flag
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- LITTLE_ENDIAN
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ur20980/src/engine/build
$ make
Scanning dependencies of target gost
[  3%] Building C object CMakeFiles/gost.dir/gost_ec_keyx.c.o
/Users/ur20980/src/engine/gost_ec_keyx.c:10:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/gost.dir/gost_ec_keyx.c.o] Error 1
make[1]: *** [CMakeFiles/gost.dir/all] Error 2
make: *** [all] Error 2
$ 
```

Other branches seem to be able to find OpenSSL installation just fine. ???

**Comment by beldmit** [comment]
На Mac были какие-то проблемы в этом месте. Где на самом деле находится файл openssl/evp.h?

**Comment by mouse07410** [comment]
```
$ ll /opt/local/include/openssl/evp.h
-rw-r--r--  1 root  admin  74935 May 29 09:49 /opt/local/include/openssl/evp.h
$ echo $OPENSSL_CFLAGS
-Os -Ofast -std=gnu17 -march=native -I/opt/local/include
$ pkg-config --cflags openssl
-I/opt/local/include
$ 
```

**Comment by beldmit** [comment]
Вот по этому поводу я готов продолжать общаться после возвращения из отпуска. 1 августа напомните пожалуйста.

**Comment by mouse07410** [comment]
Sure, no problem. Enjoy your vacation.

**Comment by mouse07410** [comment]
Ping...?

**Comment by beldmit** [comment]
Try to add the line 
```
find_package(OpenSSL 1.1 REQUIRED)
```
To the beginning of CMakeLists.txt
If it works for 1.1.1 then I'll restore it.

**Comment by mouse07410** [comment]
@beldmit here's my current `CMakeLists.txt` (modified from your master branch):
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a85c86e..d9b0992 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -8,6 +8,17 @@ include(CheckFunctionExists)
 enable_testing()
 
 find_package(OpenSSL 1.1.1 REQUIRED)
+message(STATUS "Found OpenSSL ${OPENSSL_VERSION_MAJOR}.${OPENSSL_VERSION_MINOR}.${OPENSSL_VERSION_PATCH}.${OPENSSL_VERSION_TWEAK}")
+
+if(NOT DEFINED OPENSSL_VERSION_MAJOR)
+   message(STATUS "OpenSSL version values were not properly defined (OpenSSL-3 issue), setting to 3.0")
+   set(OPENSSL_VERSION_MAJOR "3")
+   set(OPENSSL_VERSION_MINOR "0")
+endif(NOT DEFINED OPENSSL_VERSION_MAJOR)
+
+message(STATUS "Found OpenSSL includes:   ${OPENSSL_INCLUDE_DIR}")
+message(STATUS "Found OpenSSL crypto lib: ${OPENSSL_CRYPTO_LIBRARY}")
+
 include_directories(${OPENSSL_INCLUDE_DIR})
 
 if (CMAKE_C_COMPILER_ID MATCHES "Clang")
@@ -212,7 +223,7 @@ set_property(TARGET ${BINARY_TESTS_TARGETS} APPEND PROPERTY COMPILE_DEFINITIONS
 add_library(gost_core STATIC ${GOST_LIB_SOURCE_FILES})
 set_target_properties(gost_core PROPERTIES POSITION_INDEPENDENT_CODE ON)
 
-add_library(gost_engine SHARED ${GOST_ENGINE_SOURCE_FILES})
+add_library(gost_engine SHARED ${GOST_ENGINE_SOURCE_FILES} ${OPENSSL_CRYPTO_LIBRARY})
 set_target_properties(gost_engine PROPERTIES PREFIX "" OUTPUT_NAME "gost")
 set_target_properties(gost_engine PROPERTIES VERSION ${GOST_SOVERSION} SOVERSION ${GOST_SOVERSION})
 target_link_libraries(gost_engine gost_core ${OPENSSL_CRYPTO_LIBRARY})
```
[CMakeLists.txt](https://github.com/gost-engine/engine/files/3537672/CMakeLists.txt)

No problem with OpenSSL-1.1.1c:
```
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /Users/uri/src/grasshopper-engine/build
      Start  1: digest
 1/10 Test  #1: digest ...........................   Passed    0.02 sec
      Start  2: curves
 2/10 Test  #2: curves ...........................   Passed    0.08 sec
      Start  3: parameters
 3/10 Test  #3: parameters .......................   Passed    0.08 sec
      Start  4: sign/verify
 4/10 Test  #4: sign/verify ......................   Passed    0.12 sec
      Start  5: TLS
 5/10 Test  #5: TLS ..............................   Passed    1.81 sec
      Start  6: context
 6/10 Test  #6: context ..........................   Passed    0.02 sec
      Start  7: grasshopper
 7/10 Test  #7: grasshopper ......................   Passed    0.10 sec
      Start  8: keyexpimp
 8/10 Test  #8: keyexpimp ........................   Passed    0.02 sec
      Start  9: gost89
 9/10 Test  #9: gost89 ...........................   Passed    0.01 sec
      Start 10: engine
10/10 Test #10: engine ...........................   Passed    7.18 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) =   9.44 sec
```

**Comment by levitte** [comment]
That diff is weird...  You require OpenSSL 1.1.1, but then force the version to 3?????

**Comment by mouse07410** [comment]
No, according to CMake doc, you require *at least* OpenSSL 1.1.1. So, when it finds 3.0, it should happily proceed, as it apparently does. You can observe it in the logs - it compiles against 3.0 includes, and links against 3.0 libraries.
