### ISSUE TITLE
Build in FreeBSD broken after 1a4223a

### ISSUE THREAD

**Issue by f-andrey** [gost-engine/engine#131]
Hello

I'm test build in FreeBSD before commit 1a4223a module build success if disable test `test_tls`

```
/usr/local/bin/openssl version
OpenSSL 1.1.1b  26 Feb 2019
```

Now have error
```
[ 55%] Building C object CMakeFiles/gost_engine.dir/gost_pmeth.c.o
/home/andrey/engine/gost_pmeth.c:62:38: error: passing 'const EVP_PKEY_CTX *' (aka 'const struct evp_pkey_ctx_st *') to parameter of type
      'EVP_PKEY_CTX *' (aka 'struct evp_pkey_ctx_st *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    src_data = EVP_PKEY_CTX_get_data(src);
                                     ^~~
/usr/local/include/openssl/evp.h:1370:43: note: passing argument to parameter 'ctx' here
void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
                                          ^
/home/andrey/engine/gost_pmeth.c:573:38: error: passing 'const EVP_PKEY_CTX *' (aka 'const struct evp_pkey_ctx_st *') to parameter of type
      'EVP_PKEY_CTX *' (aka 'struct evp_pkey_ctx_st *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    src_data = EVP_PKEY_CTX_get_data(src);
                                     ^~~
/usr/local/include/openssl/evp.h:1370:43: note: passing argument to parameter 'ctx' here
void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
                                          ^
/home/andrey/engine/gost_pmeth.c:1052:40: error: incompatible pointer types passing 'int (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int
      (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int
      (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/usr/local/include/openssl/evp.h:1422:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/home/andrey/engine/gost_pmeth.c:1062:40: error: incompatible pointer types passing 'int (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int
      (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int
      (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/usr/local/include/openssl/evp.h:1422:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/home/andrey/engine/gost_pmeth.c:1072:40: error: incompatible pointer types passing 'int (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int
      (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int
      (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/usr/local/include/openssl/evp.h:1422:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/home/andrey/engine/gost_pmeth.c:1083:40: error: incompatible pointer types passing 'int (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int
      (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int
      (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/usr/local/include/openssl/evp.h:1422:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/home/andrey/engine/gost_pmeth.c:1091:36: error: incompatible pointer types passing 'int (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int
      (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int
      (*)(struct evp_pkey_ctx_st *, struct evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
    EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_copy);
                                   ^~~~~~~~~~~~~~
/usr/local/include/openssl/evp.h:1422:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
7 errors generated.
gmake[2]: *** [CMakeFiles/gost_engine.dir/build.make:206: CMakeFiles/gost_engine.dir/gost_pmeth.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:481: CMakeFiles/gost_engine.dir/all] Error 2
```

**Comment by beldmit** [comment]
Use 1_1_0 branch.

**Comment by f-andrey** [comment]
1_1_0 branch support openssl 1.1.1?

**Comment by beldmit** [comment]
Sure.

The master branch is compatible with OpenSSL master (in fact with openssl + some GOST-related patches).

**Comment by f-andrey** [comment]
Thanks, openssl_1_1_0 build OK

```
/usr/local/bin/openssl ciphers -V | tr ':' '\n' | grep GOST
          0xFF,0x85 - GOST2012-GOST8912-GOST8912 TLSv1 Kx=GOST     Au=GOST12 Enc=GOST89(256) Mac=GOST89
          0x00,0x81 - GOST2001-GOST89-GOST89  TLSv1 Kx=GOST     Au=GOST01 Enc=GOST89(256) Mac=GOST89
```
