### PR TITLE
gost_pmeth.c: mitigate for constness difference in copy function

### LINKED ISSUE #154: Fails to build with OpenSSL_1_1_1
The `README.md` does say that it doesn't work - but since 1.1.1 is the current standard and downgrading to 1.1.0 is both impractical and non-attractive - perhaps you can update the code to work with 1.1.1?

`master` branch fails compilation:
```
[ 37%] Building C object CMakeFiles/gost_engine.dir/gost_pmeth.c.o
/Users/ur20980/src/engine/gost_pmeth.c:62:38: error: passing 'const EVP_PKEY_CTX *' (aka 'const struct evp_pkey_ctx_st *')
      to parameter of type 'EVP_PKEY_CTX *' (aka 'struct evp_pkey_ctx_st *') discards qualifiers
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    src_data = EVP_PKEY_CTX_get_data((const EVP_PKEY_CTX *)src);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1371:43: note: passing argument to parameter 'ctx' here
void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
                                          ^
/Users/ur20980/src/engine/gost_pmeth.c:573:38: error: passing 'const EVP_PKEY_CTX *'
      (aka 'const struct evp_pkey_ctx_st *') to parameter of type 'EVP_PKEY_CTX *' (aka 'struct evp_pkey_ctx_st *')
      discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    src_data = EVP_PKEY_CTX_get_data(src);
                                     ^~~
/opt/local/include/openssl/evp.h:1371:43: note: passing argument to parameter 'ctx' here
void *EVP_PKEY_CTX_get_data(EVP_PKEY_CTX *ctx);
                                          ^
/Users/ur20980/src/engine/gost_pmeth.c:1052:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1062:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1072:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1083:40: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
        EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_mac_copy);
                                       ^~~~~~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
/Users/ur20980/src/engine/gost_pmeth.c:1091:36: error: incompatible pointer types passing 'int
      (EVP_PKEY_CTX *, const EVP_PKEY_CTX *)' (aka 'int (struct evp_pkey_ctx_st *, const struct evp_pkey_ctx_st *)') to
      parameter of type 'int (*)(EVP_PKEY_CTX *, EVP_PKEY_CTX *)' (aka 'int (*)(struct evp_pkey_ctx_st *, struct
      evp_pkey_ctx_st *)') [-Werror,-Wincompatible-pointer-types]
    EVP_PKEY_meth_set_copy(*pmeth, pkey_gost_copy);
                                   ^~~~~~~~~~~~~~
/opt/local/include/openssl/evp.h:1423:35: note: passing argument to parameter 'copy' here
                            int (*copy) (EVP_PKEY_CTX *dst,
                                  ^
7 errors generated.
make[2]: *** [CMakeFiles/gost_engine.dir/gost_pmeth.c.o] Error 1
```
 But if `-Wno-incompatible-pointer-types` is added, it compiles OK, but fails one test:
```
$ make test
Running tests...
Test project /Users/ur20980/src/engine/build
      Start  1: digest
 1/10 Test  #1: digest ...........................   Passed    0.01 sec
      Start  2: curves
 2/10 Test  #2: curves ...........................   Passed    0.03 sec
      Start  3: parameters
 3/10 Test  #3: parameters .......................   Passed    0.03 sec
      Start  4: sign/verify
 4/10 Test  #4: sign/verify ......................   Passed    0.04 sec
      Start  5: TLS
 5/10 Test  #5: TLS ..............................   Passed    0.52 sec
      Start  6: context
 6/10 Test  #6: context ..........................   Passed    0.01 sec
      Start  7: grasshopper
 7/10 Test  #7: grasshopper ......................   Passed    0.04 sec
      Start  8: keyexpimp
 8/10 Test  #8: keyexpimp ........................   Passed    0.01 sec
      Start  9: gost89
 9/10 Test  #9: gost89 ...........................   Passed    0.00 sec
      Start 10: engine
10/10 Test #10: engine ...........................***Failed    0.14 sec

90% tests passed, 1 tests failed out of 10

Total Test time (real) =   0.85 sec

The following tests FAILED:
	 10 - engine (Failed)
Errors while running CTest
make: *** [test] Error 8
```
Here's the log: 
[LastTest.master.log.txt](https://github.com/gost-engine/engine/files/3411624/LastTest.master.log.txt)

Branch `openssl_1_1_0` compiles fine, but fails the same (presumably) test:
```
Running tests...
Test project /Users/ur20980/src/engine/build
    Start 1: engine
1/2 Test #1: engine ...........................***Failed    0.99 sec
    Start 2: grasshopper
2/2 Test #2: grasshopper ......................   Passed    0.01 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   1.01 sec

The following tests FAILED:
	  1 - engine (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Here's the log from `openssl_1_1_0` branch of this repo, compiled with the standard (Macports-installed) OpenSSL_1_1_1c: 
[LastTest.log.txt](https://github.com/gost-engine/engine/files/3411575/LastTest.log.txt)

### PR DESCRIPTION
**Pull request by levitte**
The second argument for the pkey_copy function has been constified in
OpenSSL to be 3.0.  This is normally not a problem, but when passing a
pointer to such a function, the compiler does complain.

This change solves the issue by looking at the macros
OPENSSL_VERSION_MAJOR, which is new in OpenSSL to be 3.0, and set
constness based on that.

Fixes #154

### CODE REVIEW

**Comment by beldmit** [comment]
Many thanks!
I still appreciate that the master branch will become totally incompatible with 1.1.1 because of switching to EVP_MAC and similar interfaces, but for now, let's leave it here.

**Comment by levitte** [comment]
Re EVP_MAC, we *are* retaining the EVP_PKEY interface as well, so...
I assume, though, that you'll try and make this into a provider module as well, when the time comes (as soon as we have all the asym stuff in place), yeah?

**Comment by beldmit** [comment]
Sure!

I hate the current dual EVP_MD/EVP_PKEY interface because of duplicating stuff such as control, declaring etc.

**Comment by levitte** [comment]
That's not going away, I'm afraid.  After all, how do you implement things like `md5WithRSAEncryption` if not by combining two algorithms?

But, the new provider stuff is, at least in my opinion, quite a bit easier to deal with...  all you do is set up a set of tables with function pointers, boom.  More or less.

**Comment by beldmit** [comment]
I mean not combining but a dual-headed interface.
